const hotels = [
  { id: 1, name: "Marriott", location: "Amsterdam" },
  { id: 2, name: "Renelot", location: "Amsterdam" },
  { id: 3, name: "Tralala", location: "London" },
  { id: 4, name: "Grand Hotel", location: "Paris" },
  { id: 5, name: "The Plaza", location: "New York" },
  { id: 6, name: "Hotel California", location: "Los Angeles" },
  { id: 7, name: "The Ritz", location: "London" },
  { id: 8, name: "Hilton", location: "Dubai" },
  { id: 9, name: "Shangri-La", location: "Singapore" },
  { id: 10, name: "InterContinental", location: "Tokyo" },
  { id: 11, name: "Four Seasons", location: "Sydney" },
  { id: 12, name: "Mandarin Oriental", location: "Hong Kong" },
  { id: 13, name: "Waldorf Astoria", location: "Berlin" },
  { id: 14, name: "Hyatt", location: "Chicago" },
  { id: 15, name: "Fairmont", location: "Vancouver" },
  { id: 16, name: "Sofitel", location: "Brussels" },
  { id: 17, name: "The Peninsula", location: "Bangkok" },
  { id: 18, name: "Park Hyatt", location: "Beijing" },
  { id: 19, name: "Raffles", location: "Singapore" },
  { id: 20, name: "JW Marriott", location: "Seoul" },
  { id: 21, name: "The Langham", location: "Melbourne" },
  { id: 22, name: "St. Regis", location: "Abu Dhabi" },
  { id: 23, name: "Renaissance", location: "Mumbai" },
  { id: 24, name: "Le Meridien", location: "Barcelona" },
  { id: 25, name: "Conrad", location: "Bangkok" },
  { id: 26, name: "Aman Tokyo", location: "Tokyo" },
  { id: 27, name: "The Oberoi", location: "New Delhi" },
  { id: 28, name: "Taj Mahal Palace", location: "Mumbai" },
  { id: 29, name: "The Westin", location: "Seattle" },
  { id: 30, name: "Sheraton", location: "San Francisco" },
  { id: 31, name: "The Venetian", location: "Las Vegas" },
  { id: 32, name: "Caesars Palace", location: "Las Vegas" },
  { id: 33, name: "Bellagio", location: "Las Vegas" },
  { id: 34, name: "The Mirage", location: "Las Vegas" },
  { id: 35, name: "The Cosmopolitan", location: "Las Vegas" },
  { id: 36, name: "The Wynn", location: "Las Vegas" },
  { id: 37, name: "Mandarin Oriental", location: "Miami" },
  { id: 38, name: "The Edition", location: "New York" },
  { id: 39, name: "Ace Hotel", location: "Portland" },
  { id: 40, name: "Kimpton Hotel", location: "San Diego" },
  { id: 41, name: "The Standard", location: "Los Angeles" },
  { id: 42, name: "SLS Hotel", location: "Beverly Hills" },
  { id: 43, name: "Chateau Marmont", location: "Los Angeles" },
  { id: 44, name: "The Line", location: "Los Angeles" },
  { id: 45, name: "Hotel Bel-Air", location: "Los Angeles" },
  { id: 46, name: "The London", location: "New York" },
  { id: 47, name: "The Savoy", location: "London" },
  { id: 48, name: "Claridge's", location: "London" },
  { id: 49, name: "The Dorchester", location: "London" },
  { id: 50, name: "The Connaught", location: "London" },
  { id: 51, name: "The Berkeley", location: "London" },
  { id: 52, name: "The May Fair", location: "London" },
  { id: 53, name: "The Principal", location: "Manchester" },
  { id: 54, name: "Radisson Blu", location: "Edinburgh" },
  { id: 55, name: "The Balmoral", location: "Edinburgh" },
  { id: 56, name: "Hotel du Vin", location: "Glasgow" },
  { id: 57, name: "The Lowry", location: "Manchester" },
  { id: 58, name: "The Caledonian", location: "Edinburgh" },
  { id: 59, name: "Kimpton Blythswood Square", location: "Glasgow" },
  { id: 60, name: "Malmaison", location: "Birmingham" },
  { id: 61, name: "The Cube", location: "Birmingham" },
  { id: 62, name: "The Met Hotel", location: "Leeds" },
  { id: 63, name: "DoubleTree", location: "Leeds" },
  { id: 64, name: "The Royal York", location: "York" },
  { id: 65, name: "The Grand", location: "York" },
  { id: 66, name: "Hotel Indigo", location: "York" },
  { id: 67, name: "The Principal", location: "York" },
  { id: 68, name: "Hotel du Vin", location: "Cambridge" },
  { id: 69, name: "The Varsity", location: "Cambridge" },
  { id: 70, name: "Gonville Hotel", location: "Cambridge" },
  { id: 71, name: "The Royal Cambridge", location: "Cambridge" },
  { id: 72, name: "The University Arms", location: "Cambridge" },
  { id: 73, name: "Hilton", location: "Cambridge" },
  { id: 74, name: "The Tamburlaine", location: "Cambridge" },
  { id: 75, name: "The George", location: "Edinburgh" },
  { id: 76, name: "Crowne Plaza", location: "Belfast" },
  { id: 77, name: "The Fitzwilliam", location: "Belfast" },
  { id: 78, name: "The Merchant", location: "Belfast" },
  { id: 79, name: "The Europa", location: "Belfast" },
  { id: 80, name: "The Culloden", location: "Belfast" },
  { id: 81, name: "The Salthouse", location: "Ballycastle" },
  { id: 82, name: "Bishop's Gate", location: "Derry" },
  { id: 83, name: "Shipquay Hotel", location: "Derry" },
  { id: 84, name: "The Bushmills Inn", location: "Bushmills" },
  { id: 85, name: "Lough Eske Castle", location: "Donegal" },
  { id: 86, name: "Harvey's Point", location: "Donegal" },
  { id: 87, name: "Redcastle Hotel", location: "Moville" },
  { id: 88, name: "Solis Lough Eske", location: "Donegal" },
  { id: 89, name: "An Grianan", location: "Burt" },
  { id: 90, name: "The Silver Tassie", location: "Letterkenny" },
  { id: 91, name: "The Central", location: "Donegal" },
  { id: 92, name: "The Abbey", location: "Donegal" },
  { id: 93, name: "The Nesbitt Arms", location: "Ardara" },
  { id: 94, name: "The Cuan", location: "Strangford" },
  { id: 95, name: "Slieve Donard", location: "Newcastle" },
];

module.exports = hotels;
